// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function DetectEngine(arg1:string):Promise<core.GameInfo>;

export function Extract(arg1:core.GameInfo):Promise<number>;

export function Inject(arg1:core.GameInfo):Promise<number>;

export function LaunchGame(arg1:string,arg2:string):Promise<void>;
