// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {core} from '../models';

export function BuildPatcher(arg1:string,arg2:string):Promise<main.BuildPatcherResult>;

export function DetectEngine(arg1:string):Promise<core.GameInfo>;

export function Extract(arg1:core.GameInfo):Promise<number>;

export function GetProject(arg1:string):Promise<core.Project>;

export function GetSettings():Promise<main.Settings>;

export function GetToolStatus():Promise<main.ToolStatus>;

export function Inject(arg1:core.GameInfo):Promise<number>;

export function InstallPythonPackage(arg1:string):Promise<string>;

export function LaunchGame(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SaveTranslations(arg1:string,arg2:Array<core.StringEntry>):Promise<void>;

export function SelectDirectory():Promise<string>;
