// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectEngine(arg1) {
  return window['go']['main']['App']['DetectEngine'](arg1);
}

export function Extract(arg1) {
  return window['go']['main']['App']['Extract'](arg1);
}

export function Inject(arg1) {
  return window['go']['main']['App']['Inject'](arg1);
}

export function LaunchGame(arg1, arg2) {
  return window['go']['main']['App']['LaunchGame'](arg1, arg2);
}
