// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildPatcher(arg1, arg2) {
  return window['go']['main']['App']['BuildPatcher'](arg1, arg2);
}

export function DetectEngine(arg1) {
  return window['go']['main']['App']['DetectEngine'](arg1);
}

export function Extract(arg1) {
  return window['go']['main']['App']['Extract'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetToolStatus() {
  return window['go']['main']['App']['GetToolStatus']();
}

export function Inject(arg1) {
  return window['go']['main']['App']['Inject'](arg1);
}

export function InstallPythonPackage(arg1) {
  return window['go']['main']['App']['InstallPythonPackage'](arg1);
}

export function LaunchGame(arg1, arg2) {
  return window['go']['main']['App']['LaunchGame'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTranslations(arg1, arg2) {
  return window['go']['main']['App']['SaveTranslations'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
